name: app_inventario
description: "Sistema de inventario para control de stock de panadería."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Iconos modernos de iOS
  cupertino_icons: ^1.0.6
  
  # Gestión de estado (Para que los datos se actualicen en todas las pantallas)
  provider: ^6.1.1
  # Para poder subir imagenes desde la camara o galeria
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  
  # Tipografía profesional (Para el diseño de Xavier)
  google_fonts: ^6.2.1
  
  # Base de datos local (Para persistir los datos de los panes)
  sqflite: ^2.3.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  # Reglas de código limpio
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Si Xavier decide usar imágenes propias (ej: logo de la panadería), 
  # deberá descomentar estas líneas:
  # assets:
  #   - assets/images/